export const ADD_TO_CART = "ADD_TO_CART"
export const ADD_QUANTITY = "ADD_QUANTITY"
export const SUB_QUANTITY = "SUB_QUANTITY"
export const CLEAR_CART = "CLEAR_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"